### ISSUE TITLE
Has no default export

### ISSUE THREAD

**Issue by 503geek** [zingchart/zingchart-angular#1]
I've followed the steps in the readme exactly, I've tried re-installing with npm, manually adding the @types module and using yarn instead of npm.

I'm using Angular 8, Node 12 and Npm 6. It seems no matter what I do I get the following error:

`ERROR in node_modules/zingchart-angular/lib/zingchart-angular.component.d.ts(3,8): error TS1192: Module '"[...obfuscated...]/node_modules/@types/zingchart/index"' has no default export.`

Line 3 in question, which shows a compiler error, is `import zingchart from 'zingchart';` and points to the `@types` file, same as the above error.

I've tried various fixes to handle this, including writing my own `.d.ts` file what I understand to be a default export, but to no avail. I've also tried using different styles of imports (i.e. `import * as ZingchartAngularModule` or `import { ZingchartAngularModule }`)

I'm not a seasoned Angular dev, so I may just need to get more familiar with how to resolve these errors in general, and how the structure of declared exports works, but this still seems like a gap in the installation instructions. `zingchart-angular` appears to have an ambiguous dependency on the `zingchart` module. Though the core of the issue appears to be in the `@types` module, and which yarn installs automatically, but npm does not. The fundamental issue is evading me at the moment, and I'm not sure how to proceed.

**Comment by 503geek** [comment]
I'm going to try following the approach here https://blog.zingchart.com/how-to-create-charts-in-angular/ since it seems to be more detailed and I will report back.

**Comment by 503geek** [comment]
FWIW this is using the free MBD Angular Admin Dashboard as a starter - I tried it using the MDB Vue starter and was able to get it working.

**Comment by mike-schultz** [comment]
Hi @503geek , I actually did not see that @types accepted my pull request for the type definition file! It was stuck in review for weeks due to the sheer size of it. I'll look into updating that. In the meantime, I released this package with a local typedef file in src/. Can you see if that works for you?

**Comment by 503geek** [comment]
Thanks for the reply Mike. I still see `zingchart-angular@0.0.6` as the latest. I tried reinstalling, same error, then tried removing the what might've been the old @types folder and reinstalling, same error. I have a feeling I'm trying to update/install the wrong package.

**Comment by 503geek** [comment]
Oh okay I see your commit to https://github.com/DefinitelyTyped/DefinitelyTyped - I'll see if I can figure it out.

**Comment by PatrykTucki** [comment]
@mike-schultz please have a look on https://github.com/zingchart/zingchart-angular/pull/2.

**Comment by jeanettephung** [comment]
Latest version of `@types/zingchart` resolves this issue
